---

# Ansible role to install Oracle Java 8

  - name: Check If java is already installed or not
    shell: "java -version 2>&1 | grep version | awk '{print $3}' | sed 's/\"//g'"
    register: java_installed

  - name: Installed java version
    debug: "msg={{java_installed.stdout}}"

  - block:
#    - name: Download Java
#      #command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}" ## Old way to download
#      get_url:
#        url: "{{download_url}}"
#        dest: "{{java_archive}}"
#        headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie; --no-check-certificate'

    - name: 1.0 Copy the Java tar file from {{ tar_file_src }} to {{ target_folder }}
      copy: src={{ tar_file_src }} dest={{ target_folder }}
      become: yes

    - name: 1.1 Unpack archive
      #command: "tar -zxf {{java_archive}} -C {{target_folder}} creates={{java_name}}" ## Old way to untar
#      unarchive:
#        src: "{{java_archive}}"
#        dest: "{{target_folder}}"
#        remote_src: yes
      command: tar xzf {{ java_archive }}
      args:
        chdir: "{{ target_folder }}"
        creates: "{{ java_name }}"
      become: yes

    - name: 1.2 Fix ownership of {{ target_folder }}
      file: state=directory path={{java_name}} owner={{ target_folder_owner }} group={{ target_folder_owner }} recurse=yes
      become: yes

    - name: 1.3 Set/Configure JAVA_HOME in environment variables
      shell: "echo 'export JAVA_HOME={{java_name}}\nexport PATH=$JAVA_HOME/bin:$PATH' > {{java_env_file}}"
      become: yes

    - name: 1.4 Exports/Run java env file for make JAVA_HOME available globally
      shell: "echo 'source {{java_env_file}}' >> {{ bashrc_file }}"

    - name: 1.5 Exports/Run java env file for make JAVA_HOME available globally
      shell: "source {{ bashrc_file }}"

#    - name: Clean up
#      file: state=absent path={{java_archive}}

    when: java_installed.stdout == ""