---

# Ansible role to install Oracle Java 8

  - name: Check If java is already installed or not
    shell: "java -version 2>&1 | grep version | awk '{print $3}' | sed 's/\"//g'"
    register: java_installed

  - name: Installed java version
    debug: "msg={{java_installed.stdout}}"

  - block:
    - name: 1.0 Copy the Java tar file from {{ tar_file_src }} to {{ target_folder }}
      copy: src={{ tar_file_src }} dest={{ target_folder }}
      become: yes

    - name: 1.1 Unpack archive
      command: tar xzf {{ java_archive }}
      args:
        chdir: "{{ target_folder }}"
        creates: "{{ java_name }}"
      become: yes

    - name: 1.2 Fix ownership of {{ target_folder }}
      file: state=directory path={{java_name}} owner={{ target_folder_owner }} group={{ target_folder_owner }} recurse=yes
      become: yes

    - name: 1.3 Set/Configure JAVA_HOME in environment variables
      shell: "echo 'export JAVA_HOME={{java_name}}\nexport PATH=$JAVA_HOME/bin:$PATH' > {{java_env_file}}"
      become: yes

    - name: 1.4 Exports/Run java env file for make JAVA_HOME available globally
      lineinfile:
        dest: "{{ bashrc_file }}"
        state: present
        line: "source {{java_env_file}}"

    - name: 1.5 Exports/Run java env file for make JAVA_HOME available globally
      become: no
      shell: "source {{ bashrc_file }}"
      args:
        executable: /bin/bash

    when: java_installed.stdout == ""
