---
- hosts: all
  gather_facts: yes #IMPORTANT
  roles:
#    - { role: common, sudo: yes }
#    - role: java
    - role: hadoop
      vars:
        hadoop_dfs_replication: 2
        java_jre_path: "/opt/jdk1.8.0_231/jre"
        hadoop_yarn_app_mr_am_resource_mb: 4096
        hadoop_mr_map_memory_mb: 2048
        hadoop_mr_reduce_memory_mb: 2048
        hadoop_yarn_nodemanager_resource_memory_mb: 3084 #12228
        hadoop_yarn_scheduler_maximum_allocation_mb: 3084 #12228
        hadoop_yarn_scheduler_minimum_allocation_mb: 3084
        hadoop_yarn_nodemanager_vmem_check_enabled: "true"
        cluster_username: "ubuntu"
