---
#Role Java vars
hadoop_version: 2.8.5
hadoop_download_url: https://www-us.apache.org/dist/hadoop/common/hadoop-{{hadoop_version}}/hadoop-{{hadoop_version}}.tar.gz
hadoop_home_dir: /opt/hadoop/
hadoop_archive: "/opt/hadoop-{{hadoop_version}}.tar.gz"
hadoop_env_vars_file: "/root/.bashrc"