---
- name: 1.1 Update Yum.
  yum: name=* state=latest

- name: 1.2 Set SELinux to Permissive mode.
  selinux:
    policy: targeted
    state: permissive

- name: 1.3.1 Check if firewalld is installed
  dnf: name=firewalld state=installed
  tags:
   - install
   - firewalld

- name: 1.3.2 Disable firewalld
  systemd: name=firewalld enabled=no
  tags:
   - install
   - atomic
   - firewalld

- name: 1.3.3 Stop firewalld
  systemd: name=firewalld state=stopped
  ignore_errors: yes
  tags:
   - install
   - atomic
   - firewalld